//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фотостудия
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ФотостудияEntities : DbContext
    {
        public ФотостудияEntities()
            : base("name=ФотостудияEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Администратор> Администратор { get; set; }
        public virtual DbSet<Вид_услуги> Вид_услуги { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Журнал_фотосъемки> Журнал_фотосъемки { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Локация> Локация { get; set; }
        public virtual DbSet<Портфолио_фотографа> Портфолио_фотографа { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Фотограф> Фотограф { get; set; }
    }
}
