//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фотостудия
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договор
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Договор()
        {
            this.Журнал_фотосъемки = new HashSet<Журнал_фотосъемки>();
        }
    
        public int Номер_договора { get; set; }
        public int Номер_клиента { get; set; }
        public int Вид_услуги { get; set; }
        public int Номер_фотографа { get; set; }
        public int Номер_локации { get; set; }
        public System.DateTime Начало_съемки { get; set; }
        public System.DateTime Окончание_съемки { get; set; }
        public int Статус_договора { get; set; }

        public decimal Стоимость
        {
            get
            {
                decimal cost = Math.Ceiling((decimal)(Окончание_съемки - Начало_съемки).TotalHours) * Вид_услуги1.Стоимость;
                return cost == 0 ? Вид_услуги1.Стоимость : cost;
            }
        }


        public virtual Вид_услуги Вид_услуги1 { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Локация Локация { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual Фотограф Фотограф { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал_фотосъемки> Журнал_фотосъемки { get; set; }
    }
}
