//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фотостудия
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Клиент()
        {
            this.Договор = new HashSet<Договор>();
        }
    
        public int Номер_клиента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int Номер_паспорта { get; set; }
        public int Серия_паспорта { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Телефон { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }

        public string FIO
        {
            get { return $"{Фамилия.Trim()} {Имя[0]}.{Отчество[0]}."; }
        }
        public string Паспортные_данные
        {
            get
            {
                return Номер_паспорта + " / " + Серия_паспорта;
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор> Договор { get; set; }
    }
}
