//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фотостудия
{
    using System;
    using System.Collections.Generic;
    
    public partial class Портфолио_фотографа
    {
        public int Номер_портфолио { get; set; }
        public int Номер_фотографа { get; set; }
        public string Изображение { get; set; }
    
        public virtual Фотограф Фотограф { get; set; }

        public string ImageForWins
        {
            get
            {
                return AppDomain.CurrentDomain.BaseDirectory + "..\\..\\" + "Pages/imgs/" + Изображение;
            }
        }
        public string ActualImage
        {
            get
            {
                return AppDomain.CurrentDomain.BaseDirectory + "..\\..\\" + "Pages/imgs/" + Изображение;
            }
        }

    }
}
